.\" rpm - Red Hat Package Manager
.TH updfstab 8 "29 Jan 2003" "Red Hat, Inc." "Red Hat Linux"
.SH NAME
updfstab \- update /etc/fstab to reflect removable devices
.SH SYNOPSIS
\fBupdfstab\fR [\fI\-nt\fR] [\-\-usage]
.SH DESCRIPTION
\fBupdfstab\fR is designed to keep \fB/etc/fstab\fR consistent with the
devices plugged into your system. It looks for devices such as cdroms,
zip and jaz drives, ls120 drives, and digital cameras on the SCSI and IDE
buses. USB devices look like SCSI devices to user space, so those
are supported as well, but are only added if they are currently attached
to the system (having a scsi device assigned to them is not sufficient).

Devices which \fBupdfstab\fR adds to \fB/etc/fstab\fR are marked with
the \fIkudzu\fR mount option to distinguish them from other devices. 
\fBupdfstab\fR will not remove devices from \fB/etc/fstab\fR unless they
are marked with the \fIkudzu\fR mount option. It also ignores devices that
are already listed in \fB/etc/fstab\fR, or which have multiple partitions
on the media currently inserted (except when \fBignoremulti\fB is used).

.SH OPTIONS

.TP
\fB-c,-\-config\fR=\fIpath\fR
Use the configuration specified by \fIpath\fR, rather then 
/etc/updfstab.conf.

.TP
\fB-n,-\-normalize\fR

Normally, \fBupdfstab\fR tries to touch \fB/etc/fstab\fR as little as
possible. When this option is given, it will instead move all of the
devices with the \fIkudzu\fR mount option to the end of the file, and
will list the devices in the same order the internal probe returns.

.TP
\fB-t,-\-test\fR

When this option is specified, \fBupdstab\fR does not update the 
\fB/etc/fstab\fR file. Instead, it displays the fstab entries it would
use to standard out. If no changes need to be made, it outputs the
string \fI(nothing to do)\fR rather then a full filesystem table.

.SH CONFIGURATION

The devices \fRupdfstab\fI looks for are specified by its configuration file,
/etc/updfstab.conf by default. It defines a number of devices which
\fIupdfstab\fR looks for on the system, along with various attributes
of that device. If a single device name is given multiple times, later
values override those given earlier. However, \fBmatch\fR directives
accumulate; all specified matches remain in effect for that device.
The default value of flags may be changed by specifying a new value for
that flag outside of any device section, which changes the default for
all future devices.

A simple configuration file looks like this:
.nf
.ta +3i
# sample updfstab configuration file
symlink false

device cdrom {
    symlink true
    match cdrom
}

device zip {
    match hd zip
    match floppy "zip"
}
.fi

Here two devices are specified, cdrom and zip. If a cdrom device is found
on the system, a \fB/dev/cdrom\fR is created pointing to the /dev entry
for the device, and \fB/mnt/cdrom\fR is added to \fB/etc/fstab\fR. The
next entry looks for hard drive devices with \fBzip\fR in their description
as well as floppy devices with \fBzip\fR in their description. If either is
found \fB/mnt/zip\fR is added to \fB/etc/fstab\fR, but no symlink is
created.

Here is the complete list of directives which may be used:

.TP
\fBdevice \fIname\fR
Set attributes for device name \fIname\fR. The \fIname\fR is used in the
\fB/etc/fstab\fR entry and for any symbolic links which are created.

.TP
\fBinclude \fIpath\fR
Parsing of the current configuration file is stopped, and the file
specified by \fIpath\fR is read for current configuration information.
Multiple \fBinclude\fR directives may be given, but they may not appear
inside of \fBdevice\fR sections.

.TP
\fBignoremulti \fIval\fR
If \fIval\fR is true, \fBupdfstab\fR will not skip the device, even if it
has multiple partitions, and will add a mount entry to \fB/etc/fstab\fR,
using the partition specified in the config file.

.TP
\fBmatch \fIclass string\fR
This directive adds a new rule for this device type; devices found on the
system which match this rule are considered a device of the type whose section
the \fBmatch\fR directive appears in. The \fIclass\fR must be \fBcdrom\fR,
\fBfloppy\fR, or \fBhd\fR. If \fIstring\fR appears, it must be a substring
of the physical device's description for the rule to match.

.TP
\fBnofstab \fIval\fR
If \fIval\fR is true, \fBupdfstab\fR does not add a mount entry to
\fB/etc/fstab\fR. This is mainly useful in conjunction with
\fBsymlink\fR.

.TP
\fBpartition \fInum\fR
Specifies a default partition number which should be mounted from this
device. If 0 is used, no partition number appears. \fBupdfstab\fR always
scans \fB/proc/partitions\fR for the proper partition number before relying
on this value.

.TP
\fBskip \fIval\fR
The device entry is skipped. This lets a configuration file undefine
a device that was defined earlier (such as in an included file). \fIval\fR
should be \fBtrue\fR or \fBfalse\fR.

.TP
\fBsymlink \fIval\fR
If \fIval\fR is true, \fBupdfstab\fR creates a symbolic link in the
\fB/dev\fR directory pointing to the actual device. This symbolic link
is then used in \fB/etc/fstab\fR.


.SH FILES
.nf
/etc/fstab
/etc/updfstab.conf
/proc/partitions
.fi
.El
.SH SEE ALSO
.IR kudzu (1)
.nf
.SH AUTHORS
.nf
Erik Troan <ewt@redhat.com>
.fi
