/*
  Automatically generated by 'make config' -- don't edit!
*/
#ifndef _PCMCIA_CONFIG_H
#define _PCMCIA_CONFIG_H

#define AUTOCONF_INCLUDED
#define __IN_PCMCIA_PACKAGE__

#define LINUX "/usr/src/linux-2.4"
#define PREFIX ""
#define KCC "gcc"
#define UCC "cc"
#define LD "ld"
#define KFLAGS ""
#define UFLAGS ""
#define PCDEBUG ""
#define USE_PM 1
#define UNSAFE_TOOLS 1
#define CONFIG_CARDBUS 1
#define CONFIG_PNP_BIOS 1
#define MODDIR "/tmp/foo/bar"

/* Options from current kernel */
#define CONFIG_MODULES 1
#define CONFIG_PCMCIA 1
#undef  CONFIG_SMP
#define CONFIG_PCI 1
#define CONFIG_PCI_QUIRKS 1
#define CONFIG_PM 1
#define CONFIG_SCSI 1
#define CONFIG_IEEE1394 1
#define CONFIG_INET 1
#define CONFIG_NET_PCMCIA_RADIO 1
#define CONFIG_TR 1
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_NET_DIVERT
#define CONFIG_MODVERSIONS 1
#undef  CONFIG_KERNEL_DEBUGGING
#define CONFIG_X86_L1_CACHE_BYTES 32
#define CONFIG_X86_L1_CACHE_SHIFT 5
#define CONFIG_PROC_FS 1
#define CONFIG_1GB 1
#undef  CONFIG_2GB
#undef  CONFIG_3GB
#define ARCH "i386"
#define HOST_ARCH "i386"
#define AFLAGS ""
#define CONFIG_ISA 1
#define CONFIG_UID16 1

#include <linux/version.h>
#include <linux/major.h>
#define LINUX_VERSION_CODE 132098
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))

#define HAS_PROC_BUS 1
#undef NEW_AIC7XXX 
#define AIC7XXX_H <../drivers/scsi/aic7xxx/aic7xxx.h>
#define SYSV_INIT 1
#define RC_DIR "/etc/rc.d"
#undef  HAS_FORMS
#define MANDIR "/usr/man"
#define XMANDIR "/usr/X11R6/man"

#endif /* _PCMCIA_CONFIG_H */
